### ISSUE TITLE
cetic/helm-nifi apache/nifi docker environment variables

### ISSUE THREAD

**Issue by spencerdcarlson** [cetic/helm-nifi#15]
**Is your feature request related to a problem? Please describe.**
I am trying to pass in environment variables that the parent [apache/nifi](https://hub.docker.com/r/apache/nifi/) docker image supports, but seem to be disregarded by helm. Specifically `NIFI_VARIABLE_REGISTRY_PROPERTIES` which sets the value of the `nifi.variable.registry.properties=` property in the `/opt/nifi/nifi-current/conf/nifi.properties` file. Executing as a simple docker `docker run -e NIFI_VARIABLE_REGISTRY_PROPERTIES=/opt/nifi/nifi-current/conf/custom/registry-secret.properties apache/nifi` the value is set correctly from the entrypoint [start.sh](https://github.com/apache/nifi/blob/d7ca37d065677e3016477f74ecdfe233ccd725c7/nifi-docker/dockerhub/sh/start.sh#L46) script

**Describe the solution you'd like**
Support parent Dockerfile env vars
Could also expose a value to override the `nifi.variable.registry.properties` property by adding a call to
[prop_replace](https://github.com/cetic/helm-nifi/blob/e898b81faf87ee7432facbf937c71e7083995770/templates/statefulset.yaml#L109)

```bash
prop_replace nifi.variable.registry.properties ${NIFI_VARIABLE_REGISTRY_PROPERTIES}
```

**Comment by jdesroch** [comment]
One solution would be to have the chart values overwrite environment variables defined in apache/nifi in the server's command and then call the start.sh to make the configurations.  There would need to be some refactoring since start.sh also affects other files like authorizers.xml.

Trying to think of a way to get the best of both worlds; chart Values that are clearly documented and have priority, while taking advantage of the supported configuration of the docker image that is well maintained and updated as new properties are added to the application.

**Please forgive the related aside.**  I've struggled with this in developing a NiFi Puppet module as well.  How many properties do you support using explicit parameters and support for new properties.  It may be possible to overwrite any properties very flexibly like a safety valve scenario.  Something like this in values.yaml:
```
---
properties:
  nifi.variable.registry.properties: /my/variables/file
  some.other.property: foo
```
Then iterate over the properties in the command after sourcing common.sh where prop_replace is defined.
```
scripts_dir='/opt/nifi/scripts'

[ -f "${scripts_dir}/common.sh" ] && . "${scripts_dir}/common.sh"

{{- range $prop_name, $prop_value := .Values.properties }}
  prop_replace {{ $prop_name }} {{ $prop_value  }}
{{- end }}
```
If that works then a similar setup could allow flexible configuration of bootstrap.conf.  I'm just learning most of these technologies, so feel free to crush my dreams if this isn't practical.  Also not sure about how periods "." in property names will be rendered.

**Comment by jdesroch** [comment]
Hopefully I can put some time into this tomorrow but I'll look for feedback before I get started.

**Comment by jdesroch** [comment]
@spencerdcarlson @aexnuttinck I'd be interested in any feedback on my proposed solution.

**Comment by alexnuttinck** [comment]
Hello @spencerdcarlson, I will have a look, already thank you!

**Comment by alexnuttinck** [comment]
Merged in [0.2.3](https://github.com/cetic/helm-nifi/releases/tag/0.2.3).

@spencerdcarlson tell us if it is ok for you? Then, we can close this issue.

**Comment by spencerdcarlson** [comment]
@alexnuttinck, thanks for taking the time to address this. This will work for sure.

**Comment by alexnuttinck** [comment]
Thanks @spencerdcarlson @jdesroch, I close this issue.

**Comment by jdesroch** [comment]
@spencerdcarlson FYI I just learned about the latest feature that is meant to replace variable registry https://nifi.apache.org/docs/nifi-docs/html/user-guide.html#Parameters
