### ISSUE TITLE
[cetic/nifi] Any plans to support NiFi 1.14.0

### ISSUE THREAD

**Issue by aelich** [cetic/helm-nifi#160]
I tried to deploy it using this but struggle with it i  have problems with TLS handshake failing and request for nifi.sensitive.props.key . Or do you have any hint dow to do it?

even when i set up in 0.7.8  this safetyValue I still have an issue
```
nifi.sensitive.props.key: thisIsMyPassword
```
![NIFI-FIX-IMPORTANT!!!](https://user-images.githubusercontent.com/41852883/127326911-b00a8647-2d5d-4f88-a14f-2478709de538.png)

I still have an issue whenever i try to move any processor
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/41852883/127327068-852952b9-cef3-45f8-9e8b-ba08fdb05d0b.png)

```
Mixed Content: The page at 'https://nifi.akakube.io/nifi/?processGroupId=root&componentIds=ecfe9607-017a-1000-0000-0000403f7069' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://nifi.akakube.io:443/nifi-api/processors/ecfe9607-017a-1000-0000-0000403f7069'. This request has been blocked; the content must be served over HTTPS.
```

I really committed myself to NiFi to learn it, and if have any hints please help.

**Comment by zakaria2905** [comment]
The webProxyHost environment variable has been added to the start.sh file in the apache Github with the #5226 pull request.
But the nifi docker image from apache dockerhub seems that this environment variable is not present.
I think it is because the docker image has been not updated. We have to wait the update of this image.

https://apachenifi.slack.com/archives/C0L9VCD47/p1632298380217600

https://github.com/apache/nifi/pull/5226
