### ISSUE TITLE
[cetic/nifi] new nifi version

### ISSUE THREAD

**Issue by yayatab** [cetic/helm-nifi#74]
Last month, a new [NiFi version was released](https://cwiki.apache.org/confluence/display/NIFI/Release+Notes). NiFi 1.12.0 (and a week afterwards, 1.12.1)
the new release contains lot's of neccesary improvements like, new kafka version and monitoring.

Will this helm chart supports the new NiFi version? 
could you pleas add it?

**Comment by alexnuttinck** [comment]
Hello @yayatab, 
Yes you should be able to use the 1.12.0 version with this chart by modifying the tag value.
I will modify the chart to use the 1.12.1 version of nifi when the docker image is available. 
Since the PR https://github.com/cetic/helm-nifi/pull/76 needs that version to work. There is an issue with the 1.12.0.

**Comment by hobe** [comment]
Hi @alexnuttinck, 
1.12.1 of the nifi docker image is now available: https://hub.docker.com/r/apache/nifi/tags

**Comment by alexnuttinck** [comment]
thanks @hobe.

The helm chart now uses nifi 1.12.1 by default. (chart version 0.5.4)

**Comment by yayatab** [comment]
thanks @hobe  and @alexnuttinck
